<?php

return [

    'natures' => [

        'actif_financier' => [
            'compte_courant' => 'Compte courant',
            'compte_sur_livret_csl' => 'Compte sur livret (CSL)',
            'livret_de_developpement_durable_et_solidaire' => 'Livret de développement durable et solidaire',
            'livret_a' => 'Livret A',
            'livret_depargne_populaire_lep' => 'Livret d’épargne populaire (LEP)',
            'livrets_jeune' => 'Livret jeune',
            'cel' => 'CEL',
            'compte_a_terme' => 'Compte à terme',
            'compte_courant_dassocies' => 'Compte courant d’associés',
            'pel' => 'PEL',
            'pep_bancaire' => 'PEP bancaire',
            'autres_depots' => 'Autres dépôts',
            'compte_titres' => 'Compte titres',
            'pea' => 'PEA',
            'peapme' => 'PEA-PME',
            'parts_de_sofica' => 'Parts de SOFICA',
            'parts_de_fcpi' => 'Parts de FCPI',
            'parts_de_fcpr' => 'Parts de FCPR',
            'parts_de_fip' => 'Parts de FIP',
            'parts_de_holding' => 'Parts de holding',
            'girardin_industrielle' => 'Girardin industriel',
            'autres_droits_sociaux' => 'Autres droits sociaux',
            'autres_valeurs_mobilieres' => 'Autres valeurs mobilières',
            'contrat_dassurancevie_multisupports' => 'Contrat d’assurance-vie multisupports',
            'pep_assurance_vie_multisupports' => 'PEP assurance-vie multisupports',
            'bons_contrats_de_capitalisation' => 'Bons, contrats de capitalisation',
            'per' => 'PER',
            'peepei' => 'PEE / PEI',
            'percopercoi' => 'PERCO / PERCOI',
            'perp' => 'PERP',
            'contrat_loi_madelin' => 'Contrat Loi Madelin',
            'contrat_article_83' => 'Contrat article 83',
            'contrat_article_82' => 'Contrat article 82',
            'contrat_prefonretraite' => 'Contrat Préfon-Retraite',
        ],

        'actif_non_financier' => [
            'bien_dusage' => 'Bien d’usage',
            'residence_principale' => 'Résidence principale',
            'residence_secondaire' => 'Résidence secondaire',
            'terrain' => 'Terrain',
            'autre_bien_dusage' => 'Autre bien d’usage',
            'immobilier_locatif_location_en_meublee_et_parts_de_sci' => 'Immobilier locatif, location meublée et parts de SCI',
            'immobilier_locatif_locatif' => 'Immobilier locatif',
            'location_meublee_professionnelle_lmp' => 'Location meublée professionnelle (LMP)',
            'location_meublee_non_professionnelle_lmnp' => 'Location meublée non professionnelle (LMNP)',
            'location_meublee_non_professionnelle_lmnp_loi_bouvard' => 'LMNP - Loi Bouvard',
            'par_de_sci' => 'Parts de SCI',
            'scpi' => 'SCPI',
            'parts_de_scpi' => 'Parts de SCPI',
            'bien_professionnels' => 'Biens professionnels',
            'droits_sociaux' => 'Droits sociaux',
            'entreprise_individuelle' => 'Entreprise individuelle',
            'fonds_de_commerce_clienteles' => 'Fonds de commerce, clientèles',
            'autres_biens_professionnels' => 'Autres biens professionnels',
            'placement_foncier_et_divers' => 'Placement foncier et divers',
            'part_de_groupements_forestiers' => 'Parts de groupements forestiers',
            'bois_et_foret' => 'Bois et forêt',
            'bien_ruraux_loues_a_long_terme' => 'Biens ruraux loués à long terme',
            'parts_de_gfa_gaf_gfv_et_gfr' => 'Parts de GFA, GAF, GFV et GFR',
            'parts_de_societe_depargne_forestiere' => 'Parts de société d’épargne forestière',
            'objet_dart_et_dantiquites' => 'Objets d’art et antiquités',
            'or_dematerialise_compte_titres' => 'Or dématérialisé',
            'or_physique_lingots_pieces_etc' => 'Or physique',
            'autres_placements_divers' => 'Autres placements divers',
        ],

        'passif' => [
            'emprunt_sur_residence_principale' => 'Emprunt sur résidence principale',
            'emprunt_sur_residence_secondaire' => 'Emprunt sur résidence secondaire',
            'emprunt_immobilier_locatif' => 'Emprunt immobilier locatif',
            'credit_a_la_consommation' => 'Crédit à la consommation',
            'credit_auto' => 'Crédit auto',
            'credit_renouvelable' => 'Crédit renouvelable (revolving)',
            'pret_personnel' => 'Prêt personnel',
            'pret_etudiant' => 'Prêt étudiant',
            'decouvert_bancaire' => 'Découvert bancaire',
            'dette_fiscale' => 'Dette fiscale (IR, IFI)',
            'caution_garantie_donnee' => 'Caution / garantie donnée',
            'autres_dettes_diverses' => 'Autres dettes diverses',
        ],

        'revenu' => [
            'salaires_traitements' => 'Salaires et traitements',
            'revenus_bic' => 'Revenus industriels et commerciaux (BIC)',
            'revenus_bnc' => 'Revenus non commerciaux (BNC)',
            'revenus_ba' => 'Revenus agricoles (BA)',
            'revenus_fonciers' => 'Revenus fonciers',
            'pensions_retraites' => 'Pensions et retraites',
            'rentes_viageres' => 'Rentes viagères',
            'revenus_capitaux_mobiliers' => 'Revenus de capitaux mobiliers (dividendes, intérêts)',
            'allocations' => 'Allocations (chômage, familiales, etc.)',
            'autres_revenus' => 'Autres revenus',
        ],

        'charge' => [
            'loyer_verse' => 'Loyer versé',
            'mensualites_credits' => 'Mensualités de crédits',
            'impot_revenu' => 'Impôt sur le revenu',
            'ifi' => 'Impôt sur la fortune immobilière (IFI)',
            'taxe_fonciere' => 'Taxe foncière',
            'charges_copropriete' => 'Charges de copropriété',
            'pension_alimentaire_versee' => 'Pension alimentaire versée',
            'cotisations_sociales_retraite' => 'Cotisations sociales et retraite complémentaire',
            'assurances' => 'Assurances (habitation, prévoyance, santé...)',
            'frais_scolarite_garde' => 'Frais de scolarité et garde d’enfants',
            'autres_charges' => 'Autres charges courantes',
        ],

    ],

    'types_pret' => [
        'amortissable' => 'Amortissable',
        'in_fine' => 'In fine',
        'pret_relais' => 'Prêt relais',
        'pret_taux_zero' => 'Prêt à taux zéro (PTZ)',
        'pret_conventionne' => 'Prêt conventionné',
        'autre' => 'Autre',
    ],

    'objectifs' => [
        'optimiser_rentabilite_placements' => 'Optimiser la rentabilité de ses placements',
        'preparer_retraite' => 'Préparer sa retraite',
        'reduire_fiscalite' => 'Réduire sa fiscalité',
        'preparer_transmission' => 'Préparer la transmission de son patrimoine',
        'generer_revenus_complementaires' => 'Générer des revenus complémentaires',
        'constituer_epargne_precaution' => 'Se constituer une épargne de précaution',
        'financer_projet' => 'Financer un projet',
        'proteger_famille' => 'Protéger sa famille',
        'autre' => 'Autre',
    ],

    'bien' => [
        'propre' => 'Propre',
        'commun' => 'Communauté',
        'conjoint' => 'Conjoint',
        'indivision' => 'Indivision',
    ],

];
