<?php

/**
 * Formules des 51 champs calculés du questionnaire Profil investisseur,
 * dans l'ordre d'origine du formulaire JetFormBuilder (une formule peut référencer
 * le résultat d'une formule précédente dans cet ordre). Généré automatiquement,
 * ne pas éditer à la main. Syntaxe : voir App\Services\FormulaEvaluator.
 *
 * Correction appliquée : score_capacite_subir_pertes_echelle référençait dans
 * l'export d'origine un champ inexistant (a4_capacite_subir_pertes_resultats),
 * bug de l'ancien site (toujours "Très faible"). Corrigé pour référencer
 * score_capacite_subir_pertes, validé avec Niels le 26/08/2026.
 */

return [
    ['name' => 'niveau_connaissance_simple', 'formula' => '(  (%assurance_vie_et_capitalisation_profil_investisseur% || 0)  + (%reponse_1_assurance_vie_et_capitalisation_profil_investisseur% || 0)  + (%reponse_2_assurance_vie_et_capitalisation_profil_investisseur% || 0)  + (%pea_et_comptes_titres_profil_investisseur% || 0)  + (%reponse_1_pea_et_comptes_titres_profil_investisseur% || 0)  + (%reponse_2_pea_et_comptes_titres_profil_investisseur% || 0)  + (%epargne_retraite_et_entreprise_profil_investisseur% || 0)  + (%reponse_1_epargne_retraite_et_entreprise_profil_investisseur% || 0)  + (%epargne_salariale_profil_investisseur% || 0)  + (%reponse_1_epargne_salariale_profil_investisseur% || 0)  + (%connaissance_fonds_euros_profil_investisseur% || 0)  + (%reponse_1_fonds_euros_profil_investisseur% || 0)  + (%connaissance_produits_monetaires_profil_investisseur% || 0)  + (%reponse_1_produits_monetaires_profil_investisseur% || 0)  + (%connaissance_produits_obligataires_profil_investisseur% || 0)  + (%reponse_1_produits_obligataires_profil_investisseur% || 0)  + (%connaissance_produits_actions_profil_investisseur% || 0)  + (%reponse_1_produits_actions_profil_investisseur% || 0)) / 80 * 10'],
    ['name' => 'niveau_experience_simple', 'formula' => '(  (%reponse_2_fonds_euros_profil_investisseur% || 0)  + (%reponse_2_produits_monetaires_profil_investisseur% || 0)  + (%reponse_2_produits_obligataires_profil_investisseur% || 0)  + (%reponse_2_produits_actions_profil_investisseur% || 0)) / 40 * 10'],
    ['name' => 'niveau_connaissance_intermediaire', 'formula' => '(  (%connaissance_scpi_profil_investisseur% || 0)  + (%reponse_1_scpi_profil_investisseur% || 0)  + (%connaissance_ocpi_profil_investisseur% || 0)  + (%reponse_1_ocpi_profil_investisseur% || 0)  + (%connaissance_capital_investissement_ou_private_equity_fcpr_fcpi_fip_profil_investisseur% || 0)  + (%reponse_1_capital_investissement_ou_private_equity_fcpr_fcpi_fip_profil_investisseur% || 0)  + (%connaissance_produits_structures_titres_de_creance_structures_profil_investisseur% || 0)  + (%reponse_1_produits_structures_titres_de_creance_structures_profil_investisseur% || 0)  + (%connaissance_sofica_profil_investisseur% || 0)  + (%reponse_1_sofica_profil_investisseur% || 0)  + (%connaissance_produits_obligataires_complexes_profil_investisseur% || 0)  + (%reponse_1_produits_obligataires_complexes_profil_investisseur% || 0)  + (%connaissance_produits_actions_complexes_profil_investisseur% || 0)  + (%reponse_1_produits_actions_complexes_profil_investisseur% || 0)) / 70 * 10'],
    ['name' => 'niveau_experience_intermediaire', 'formula' => '(  (%reponse_2_scpi_profil_investisseur% || 0)  + (%reponse_2_ocpi_profil_investisseur% || 0)  + (%reponse_2_capital_investissement_ou_private_equity_fcpr_fcpi_fip_profil_investisseur% || 0)  + (%reponse_2_produits_structures_titres_de_creance_structures_profil_investisseur% || 0)  + (%reponse_2_sofica_profil_investisseur% || 0)  + (%reponse_2_produits_obligataires_complexes_profil_investisseur% || 0)  + (%reponse_2_produits_actions_complexes_profil_investisseur% || 0)) / 70 * 10'],
    ['name' => 'niveau_connaissance_complexe', 'formula' => '(  (%connaissance_tracker_profil_investisseur% || 0)  + (%reponse_1_tracker_profil_investisseur% || 0)  + (%connaissance_cfd_profil_investisseur% || 0)  + (%reponse_1_cfd_profil_investisseur% || 0)  + (%connaissance_futures_profil_investisseur% || 0)  + (%reponse_1_futures_profil_investisseur% || 0)  + (%connaissance_options_profil_investisseur% || 0)  + (%reponse_1_options_profil_investisseur% || 0)  + (%connaissance_warrants_profil_investisseur% || 0)  + (%reponse_1_warrants_profil_investisseur% || 0)  + (%connaissance_turbos_profil_investisseur% || 0)  + (%reponse_1_turbos_profil_investisseur% || 0)) / 60 * 10'],
    ['name' => 'niveau_experience_complexe', 'formula' => '(  (%reponse_2_tracker_profil_investisseur% || 0)  + (%reponse_2_cfd_profil_investisseur% || 0)  + (%reponse_2_futures_profil_investisseur% || 0)  + (%reponse_2_options_profil_investisseur% || 0)  + (%reponse_2_warrants_profil_investisseur% || 0)  + (%reponse_2_turbos_profil_investisseur% || 0)) / 60 * 10'],
    ['name' => 'score_complexe_resultat', 'formula' => '(( (%niveau_connaissance_intermediaire% || 0)+ (%niveau_connaissance_complexe% || 0) )/ 20) * 10'],
    ['name' => 'score_complexe_echelle', 'formula' => '(%score_complexe_resultat% <= 2) ? "🔴 Non adapté" : (%score_complexe_resultat% <= 4) ? "🟠 Connaissance limitée" : (%score_complexe_resultat% <= 6) ? "🟠 Connaissance intermédiaire" : (%score_complexe_resultat% <= 8) ? "🟢 Bonne maîtrise" : "🟢 Expertise"'],
    ['name' => 'score_connaissance_global', 'formula' => '((%niveau_connaissance_simple% || 0) * 0.3)+ ((%niveau_connaissance_intermediaire% || 0) * 0.3)+ ((%niveau_connaissance_complexe% || 0) * 0.4)'],
    ['name' => 'score_connaissance_global_echelle', 'formula' => '(%score_connaissance_global% <= 2) ? "🔴 Très faible" : (%score_connaissance_global% <= 4) ? "🟠 Faible" : (%score_connaissance_global% <= 6) ? "🟢 Bonne" : (%score_connaissance_global% <= 8) ? "🟢 Avancée" : "🟢 Expertise"'],
    ['name' => 'score_experience_global', 'formula' => '((%niveau_experience_simple% || 0) * 0.2)+ ((%niveau_experience_intermediaire% || 0) * 0.35)+ ((%niveau_experience_complexe% || 0) * 0.45)'],
    ['name' => 'score_experience_global_echelle', 'formula' => '(%score_experience_global% <= 2) ? "🔴 Débutant" : (%score_experience_global% <= 4) ? "🟠 Basique" : (%score_experience_global% <= 6) ? "🟢 Intermédiaire" : (%score_experience_global% <= 8) ? "🟢 Avancé" : "🟢 Expert"'],
    ['name' => 'score_capacite_financiere', 'formula' => '(  (%risque_4_profil_investisseur% || 0)  + (%risque_5_profil_investisseur% || 0)  + (%risque_6_profil_investisseur% || 0)  + (%risque_7_profil_investisseur% || 0)  + (%risque_8_profil_investisseur% || 0)) / 50 * 10'],
    ['name' => 'score_capacite_financiere_echelle', 'formula' => '(%score_capacite_financiere% <= 2) ? "🔴 Très faible" : (%score_capacite_financiere% <= 4) ? "🟠 Faible" : (%score_capacite_financiere% <= 6) ? "🟢 Adéquate" : (%score_capacite_financiere% <= 8) ? "🟢 Confortable" : "🟢 Très confortable"'],
    ['name' => 'score_contrainte_financiere', 'formula' => '(  (%risque_9_profil_investisseur% || 0)  + (%risque_10_profil_investisseur% || 0)  + (%risque_11_profil_investisseur% || 0)  + (%risque_12_profil_investisseur% || 0)  + (%risque_13_profil_investisseur% || 0)) / 50 * 10'],
    ['name' => 'd1_tolerance_declarative', 'formula' => '(  (%aversion_1_profil_investisseur% || 0)  + (%aversion_2_profil_investisseur% || 0)  + (%aversion_4_profil_investisseur% || 0)  + (%aversion_5_profil_investisseur% || 0)  + (%aversion_6_profil_investisseur% || 0)  + (%aversion_7_profil_investisseur% || 0)) / 60 * 10'],
    ['name' => 'd3_comportement_risque', 'formula' => '(  (%aversion_3_profil_investisseur% || 0)  + (%aversion_8_profil_investisseur% || 0)  + (%aversion_9_profil_investisseur% || 0)  + (%aversion_10_profil_investisseur% || 0)  + (%aversion_11_profil_investisseur% || 0)) / 50 * 10'],
    ['name' => 'score_tolerance_risque', 'formula' => '((%d1_tolerance_declarative% || 0) * 0.5)+ ((%d3_comportement_risque% || 0) * 0.5)'],
    ['name' => 'score_tolerance_risque_echelle', 'formula' => '(%score_tolerance_risque% <= 2) ? "🔴 Très faible" : (%score_tolerance_risque% <= 4) ? "🔴 Faible" : (%score_tolerance_risque% <= 6) ? "🟠 Modérée" : (%score_tolerance_risque% <= 8) ? "🟢 Modérée à élevée" : "🟢 Élevée"'],
    ['name' => 'score_capacite_subir_pertes', 'formula' => '(  (    (%score_capacite_financiere% || 0)    - (%score_contrainte_financiere% || 0)    + (%score_tolerance_risque% || 0)    + (%preference_1_profil_investisseur% || 0)  ) < 0) ? 0:(  (%score_capacite_financiere% || 0)  - (%score_contrainte_financiere% || 0)  + (%score_tolerance_risque% || 0)  + (%preference_1_profil_investisseur% || 0)) / 30 * 10'],
    ['name' => 'score_capacite_subir_pertes_echelle', 'formula' => '(%score_capacite_subir_pertes% <= 2) ? "Très faible": (%score_capacite_subir_pertes% <= 4) ? "Faible": (%score_capacite_subir_pertes% <= 6) ? "Modérée": (%score_capacite_subir_pertes% <= 8) ? "Élevée": "Très élevée"'],
    ['name' => 'profil_risque_final', 'formula' => '(  (%score_connaissance_global% || 0)  + (%score_experience_global% || 0)  + (%score_capacite_subir_pertes% || 0)) / 30 * 10'],
    ['name' => 'profil_risque_final_echelle', 'formula' => '(%profil_risque_final% <= 2) ? "Conservateur": (%profil_risque_final% <= 4) ? "Prudent": (%profil_risque_final% <= 6) ? "Équilibré": (%profil_risque_final% <= 8) ? "Équilibré dynamique": "Dynamique"'],
    ['name' => 'alerte_client_fragile', 'formula' => '(  (%score_capacite_subir_pertes% <= 2)  || (%score_capacite_financiere% <= 2)  || ((%score_contrainte_financiere% >= 8) && (%score_capacite_financiere% <= 4))) ? 2: (  (%score_capacite_subir_pertes% <= 4)  || ((%score_contrainte_financiere% >= 6) && (%score_capacite_financiere% <= 4))) ? 1: 0'],
    ['name' => 'alerte_client_fragile_echelle', 'formula' => '(%alerte_client_fragile% == 2) ? "🔴 Client fragile" : (%alerte_client_fragile% == 1) ? "🟠 Vigilance" : "🟢 Profil cohérent"'],
    ['name' => 'alerte_objectif_levier', 'formula' => '((%score_tolerance_risque% - %score_capacite_financiere%) > 5) ? 2: ((%score_tolerance_risque% - %score_capacite_financiere%) > 3) ? 1: 0'],
    ['name' => 'alerte_objectif_levier_echelle', 'formula' => '(%alerte_objectif_levier% == 2) ? "🔴 Incohérence forte – tolérance incompatible avec la capacité financière": (%alerte_objectif_levier% == 1) ? "🟠 Vigilance – objectif ambitieux": "🟢 Cohérent" '],
    ['name' => 'alerte_detention_sans_experience_marche', 'formula' => '((%score_connaissance_global% <= 2) && (%score_experience_global% <= 2)) ? 2: ((%score_connaissance_global% < 5) || (%score_experience_global% < 5)) ? 1: 0'],
    ['name' => 'alerte_detention_sans_experience_marches_echelle', 'formula' => '(%alerte_detention_sans_experience_marche% == 2) ? "🔴 Détention incohérente – connaissance et expérience insuffisantes" : (%alerte_detention_sans_experience_marche% == 1) ? "🟠 Expérience ou connaissance limitée" : "🟢 Cohérent"'],
    ['name' => 'alerte_profil_instable', 'formula' => '((%d1_tolerance_declarative% >= 8) && (%d3_comportement_risque% <= 4)) ? 2: ((%d1_tolerance_declarative% >= 6) && (%d3_comportement_risque% <= 5)) ? 1: 0'],
    ['name' => 'alerte_profil_instable_echelle', 'formula' => '(%alerte_profil_instable% == 2) ? "🔴 Profil instable – contradiction forte déclaratif / comportemental" : (%alerte_profil_instable% == 1) ? "🟠 Vigilance – légère instabilité du profil" : "🟢 Profil stable"'],
    ['name' => 'alerte_effort_epargne', 'formula' => '((%risque_6_profil_investisseur% >= 8) && (%risque_5_profil_investisseur% <= 3)) ? 2: ((%risque_6_profil_investisseur% >= 5) && (%risque_5_profil_investisseur% <= 3)) ? 1: 0'],
    ['name' => 'alerte_effort_epargne_echelle', 'formula' => '(%alerte_effort_epargne% == 2) ? "🔴 Effort d\'épargne excessif – situation non soutenable" : (%alerte_effort_epargne% == 1) ? "🟠 Effort d\'épargne élevé – vigilance" : "🟢 Effort d\'épargne cohérent"'],
    ['name' => 'alerte_complexes_sans_experience', 'formula' => '((%niveau_connaissance_complexe% <= 2) && (%niveau_experience_complexe% <= 2)) ? 2: ((%niveau_connaissance_complexe% < 5) || (%niveau_experience_complexe% < 5)) ? 1: 0'],
    ['name' => 'alerte_complexes_sans_experience_echelle', 'formula' => '(%alerte_complexes_sans_experience% == 2) ? "🔴 Produits complexes interdits" : (%alerte_complexes_sans_experience% == 1) ? "🟠 Vigilance produits complexes" : "🟢 Cohérent"'],
    ['name' => 'alerte_horizon_incompatible', 'formula' => '((%preference_2_profil_investisseur% <= 3) && (%profil_risque_final% >= 7)) ? 2: ((%preference_2_profil_investisseur% <= 4) && (%profil_risque_final% >= 6)) ? 1: 0'],
    ['name' => 'alerte_horizon_incompatible_echelle', 'formula' => '(%alerte_horizon_incompatible% == 2) ? "🔴 Horizon incompatible avec le profil de risque" : (%alerte_horizon_incompatible% == 1) ? "🟠 Vigilance – horizon court pour ce profil" : "🟢 Cohérent"'],
    ['name' => 'blocage_depense_imprevue', 'formula' => '(%risque_12_profil_investisseur% >= 10) ? 2: (%risque_12_profil_investisseur% >= 5) ? 1: 0'],
    ['name' => 'blocage_produits_complexes_interdits', 'formula' => '((%produits_effet_de_levier_et_produits_boursiers_profil_investisseur% >= 1) && (%niveau_connaissance_complexe% <= 2) && (%niveau_experience_complexe% <= 2)) ? 2 : ((%produits_effet_de_levier_et_produits_boursiers_profil_investisseur% >= 1) && ((%niveau_connaissance_complexe% < 5) || (%niveau_experience_complexe% < 5))) ? 1 : 0'],
    ['name' => 'coherence_bloc_1', 'formula' => '(  (%blocage_produits_complexes_interdits% == 2)  || (%blocage_depense_imprevue% == 2)  || (%alerte_client_fragile% == 2)  || (%alerte_objectif_levier% == 2)  || (%alerte_detention_sans_experience_marche% == 2)) ? 2: (  (%blocage_produits_complexes_interdits% == 1)  || (%blocage_depense_imprevue% == 1)  || (%alerte_client_fragile% == 1)  || (%alerte_objectif_levier% == 1)  || (%alerte_detention_sans_experience_marche% == 1)) ? 1: 0'],
    ['name' => 'coherence_bloc_1_echelle', 'formula' => '(%coherence_bloc_1% == 2) ? "🔴 Incohérences détectées" : (%coherence_bloc_1% == 1) ? "🟠 Points d\'attention détectés" : "🟢 Profil cohérent"'],
    ['name' => 'engagement_extra_financier_score', 'formula' => '(%extra_financier_1_profil_investisseur% || 0)'],
    ['name' => 'orientation_extra_financier_score', 'formula' => '((%extra_financier_2_profil_investisseur% || 0) / 9) * 10'],
    ['name' => 'thematiques_esg_score', 'formula' => '((%extra_financier_3_profil_investisseur% || 0) / 9) * 10'],
    ['name' => 'intensite_extra_financier_score', 'formula' => '(%extra_financier_4_profil_investisseur% || 0)'],
    ['name' => 'engagement_extra_financier_echelle', 'formula' => '(%engagement_extra_financier_score% <= 0) ? "Aucune préférence ESG" : "Client sensible ESG"'],
    ['name' => 'orientation_extra_financier_echelle', 'formula' => '(%orientation_extra_financier_score% <= 0) ? "🔴 Aucune orientation ESG" : (%orientation_extra_financier_score% <= 3.5) ? "🟠 Orientation ESG légère" : (%orientation_extra_financier_score% < 7) ? "🟠 Orientation ESG modérée" : "🟢 Orientation ESG affirmée"'],
    ['name' => 'thematiques_esg_echelle', 'formula' => '(%thematiques_esg_score% <= 0) ? "Aucune préférence thématique" :(%thematiques_esg_score% <= 3.5) ? "Sensibilité thématique faible" :(%thematiques_esg_score% <= 7) ? "Sensibilité thématique modérée" :"Sensibilité thématique forte"'],
    ['name' => 'rintensite_extra_financier_echelle', 'formula' => '(%intensite_extra_financier_score% <= 0) ? "Part non renseignée" :(%intensite_extra_financier_score% <= 2) ? "Engagement ESG limité" :(%intensite_extra_financier_score% <= 6) ? "Engagement ESG significatif" :"Engagement ESG prioritaire"'],
    ['name' => 'score_esg', 'formula' => '(%engagement_extra_financier_score% <= 0) ? 0 : (((%orientation_extra_financier_score% || 0) +(%thematiques_esg_score% || 0) +(%intensite_extra_financier_score% || 0)) / 3)'],
    ['name' => 'alerte_esg_echelle', 'formula' => '(%score_esg% <= 0) ? "🔴 Aucune préférence ESG" : (%score_esg% <= 3) ? "🟠 Sensibilité ESG faible" : (%score_esg% <= 6) ? "🟢 Sensibilité ESG modérée" : (%score_esg% <= 8) ? "🟢 Sensibilité ESG affirmée" : "🟢 Préférences ESG fortes"'],
];
